name: either_dart
description: Error handler library for type-safe and easy work with errors on Dart and Flutter. Either is an alternative to Nullable value and Exceptions.
version: 0.0.2
homepage: https://github.com/avdosev
repository: https://github.com/avdosev/either_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test_coverage: ^0.4.2
  test: ^1.15.3
